apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componenta-devfile-sample-go-basic-private-devfile-nested-dutc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mqoj-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-dutc@sha256:c52a491345366bec8229ae1a904263bc8c79f9488f5929672d83f6ecf763c319
        name: my-go
        resources: {}
status: {}
